version: "3.8"
services:
  server:
    build: 
        dockerfile: './server/Dockerfile'
    ports:
      - "3000:3000"
    links:
      - client
   client:
    build: 
        dockerfile: './client/Dockerfile'
    ports:
      - "8080:8080"