version: "3.8"
services:
  server:
    build:
      context: "../server"
    ports:
      - "3000:3000"
    links:
      - client
  client:
    build:
      context: "../client"
    ports:
      - "8080:8080"
